events {}

http {
	include mime.types;
	default_type application/octet-stream;

	upstream server_django {
		server 0.0.0.0:8000;
	}
	server {
		listen 80;

		location / {
			proxy_pass http://server_django;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $host;
			proxy_redirect off;
		}

		location /dist/ {
			alias /home/cedric/Asia/GPIO-Manager/dist/;
		}
	}
}
