events {}

http {
	include mime.types;
	default_type application/octet-stream;

	server {
		listen 8000;
		server_name 127.0.0.1;

		location / {
			proxy_pass http://unix:/run/gunicorn.sock;
		}

		location /dist/ {
			alias /home/cedric/Asia/GPIO-Manager/dist/;
		}
	}
}
